
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STYLiSH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STYLiSH
  use_frameworks!
  pod 'Kingfisher', '~> 7.12.0'
  pod 'MJRefresh', '~> 3.7.0'
  pod 'Alamofire', '~> 5.9.0'
  pod 'IQKeyboardManagerSwift', '~> 7.1.0'
  pod 'StatusAlert', '~> 1.1.0'

end
